old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
      lazy: true
      connection_timeout: 3
      read_write_timeout: 3

  producers:
    update_statistics:
      connection: default
      exchange_options: { name: 'update_statistics', type: direct }

  consumers:
    update_statistics:
      connection: default
      exchange_options: { name: 'update_statistics', type: direct }
      queue_options:
        name: 'update_statistics'
        routing_keys: [ 'update_statistics' ]
      callback: App\Application\Consumer\UpdateStatistics\Consumer
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      enable_logger: true
