security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Domain\Entity\User:
      algorithm: auto

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Domain\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Application\Security\JwtAuthenticator
      stateless: true
      entry_point: App\Application\Security\JwtAuthenticator

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/refresh-token, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: ROLE_USER }