services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-dev}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    container_name: easy_trip_fpm
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: easy_trip_nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    container_name: easy_trip_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: root
      POSTGRES_DB: easy_trip
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  rabbitmq:
    image: rabbitmq:3-management
    working_dir: /app
    hostname: rabbit-mq
    container_name: 'rabbit-mq'
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: root

volumes:
  db_data: