services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PUID: 1000
        PGID: 1000
    container_name: easy_trip_fpm
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: easy_trip_nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  postgres:
    image: postgres:15-alpine
    container_name: easy_trip_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: root
      POSTGRES_DB: easy_trip
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: