# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Application\EventListener\KernelViewEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  App\Application\EventListener\KernelExceptionEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  App\Application\EventListener\RoleCheckEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  App\Controller\CLI\UpdateStatisticsCommand:
    arguments:
      $updateStatisticsProducer: '@old_sound_rabbit_mq.update_statistics_producer'