# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    jwt_secret: '%env(JWT_SECRET)%'
    jwt_token_ttl: 3600
    jwt_refresh_token_ttl: 86400

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Application\EventListener\KernelViewEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  App\Application\EventListener\KernelExceptionEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  App\Application\EventListener\RoleCheckEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  App\Infrastructure\Bus\RabbitMqBus:
    calls:
      - [ 'registerProducer', [ !php/enum App\Infrastructure\Bus\AmqpExchangeEnum::UpdateStatistics, '@old_sound_rabbit_mq.update_statistics_producer' ] ]

  App\Application\Security\JwtEncoder:
    arguments:
      $params: '@parameter_bag'
      $secret: '%jwt_secret%'
      $algorithm: 'HS256'
      $tokenTtl: '%jwt_token_ttl%'

  App\Application\Security\TokenManager:
    arguments:
      $params: '@parameter_bag'
      $jwtEncoder: '@App\Application\Security\JwtEncoder'
      $entityManager: '@doctrine.orm.entity_manager'

  App\Application\Security\UserProvider:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'